/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinal.ui.formularios;

import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import proyectofinal.CrearArchivos;
import proyectofinal.objetos.Arma;
import proyectofinal.objetos.Avion;
import proyectofinal.objetos.Jugador;
import proyectofinal.objetos.Tanque;
import proyectofinal.objetos.Vehiculo;

/**
 *
 * @author James
 */
public class CrearVehiculoDialog extends javax.swing.JDialog {
    private Jugador jugador;
    private Vehiculo vehiculo;
    private CrearArchivos<Vehiculo> archivosVehiculos;
    private CrearArchivos<Arma> archivosArma;
    private DialogImagenesAviones imagenesAviones;
    private DialogImagenesTanques imagenesTanques;
    /**
     * Creates new form CrearVehiculoDialog
     */
    public CrearVehiculoDialog(java.awt.Frame parent, boolean modal, Jugador jugador, CrearArchivos<Vehiculo> archivosVehiculos, CrearArchivos<Arma> archivosArma) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.archivosArma = archivosArma;
        this.jugador = jugador;
        this.archivosVehiculos = archivosVehiculos;
        this.imagenesAviones  = new DialogImagenesAviones(parent, true, this);
        this.imagenesTanques  = new DialogImagenesTanques(parent, true, this);
        lblValidar.setVisible(false);
    }

    public void agregarLblImagen(String url) {
        this.lblImagen.setIcon(new  ImageIcon(url));
         lblImagen.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBienvenido = new javax.swing.JLabel();
        lblNombreDelVehiculo = new javax.swing.JLabel();
        txtNombreDelVehiculo = new javax.swing.JTextField();
        comboBox = new javax.swing.JComboBox<>();
        lblTipoDeVehiculo = new javax.swing.JLabel();
        botonCrear = new javax.swing.JButton();
        botonAgregar = new javax.swing.JButton();
        lblValidar = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblImagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblBienvenido.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblBienvenido.setText("Bienvenido puedes crearte 3 vehiculos como maximo:");

        lblNombreDelVehiculo.setText("Nombre del Vehiculo:");

        comboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Avion", "Tanque" }));

        lblTipoDeVehiculo.setText("Tipo de Vehiculo:");

        botonCrear.setText("Crear");
        botonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearActionPerformed(evt);
            }
        });

        botonAgregar.setText("Selecciona su imagen");
        botonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarActionPerformed(evt);
            }
        });

        lblValidar.setForeground(new java.awt.Color(255, 0, 0));
        lblValidar.setText("Todos los campos necesarios.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblImagen, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNombreDelVehiculo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtNombreDelVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(29, 29, 29)
                                        .addComponent(lblTipoDeVehiculo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblValidar)))
                            .addComponent(lblBienvenido)
                            .addComponent(botonCrear))
                        .addGap(0, 84, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(botonAgregar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBienvenido)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombreDelVehiculo)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNombreDelVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblTipoDeVehiculo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblValidar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonAgregar)
                .addGap(42, 42, 42)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonCrear)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearActionPerformed
        // TODO add your handling code here:
        if (txtNombreDelVehiculo.getText().isEmpty() || lblImagen.getIcon() == null) {
            lblValidar.setVisible(true);
        } else {
            try {
                if (comboBox.getSelectedItem().toString().equalsIgnoreCase("Avion")) {
                    vehiculo = new Avion(txtNombreDelVehiculo.getText(), lblImagen, false);
                } else {
                    vehiculo = new Tanque(txtNombreDelVehiculo.getText(), lblImagen, false);
                }
                vehiculo.agregarValoresIniciales();
                agregarArmas(vehiculo);
                jugador.agregarVehiculosEnBatallas((Vehiculo)vehiculo.clone());
                if (vehiculo instanceof Avion) {
                    archivosVehiculos.crearArchivo((Vehiculo)vehiculo.clone(), "Avion", vehiculo.getNombreVehiculo(), ".ve");
                } else {
                    archivosVehiculos.crearArchivo((Vehiculo)vehiculo.clone(), "Tanque", vehiculo.getNombreVehiculo(), ".ve");
                }
                JOptionPane.showMessageDialog(this, "Creado");
                txtNombreDelVehiculo.setText("");
                lblImagen.setVisible(false);
                this.setVisible(false);
            } catch (CloneNotSupportedException ex) {
                System.out.println("No se puede Clonar");
            }
        }
    }//GEN-LAST:event_botonCrearActionPerformed

    private void botonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarActionPerformed
        // TODO add your handling code here:
        if (comboBox.getSelectedItem().toString().equalsIgnoreCase("Avion")) {
            imagenesAviones.setVisible(true);
        } else {
            imagenesTanques.setVisible(true);
        }
        this.lblImagen.setIcon(lblImagen.getIcon());
    }//GEN-LAST:event_botonAgregarActionPerformed

    private void agregarArmas(Vehiculo vehiculo) {
        Random random = new Random();
        vehiculo.agregarArmas(archivosArma.leerListaDeArchivos(".arm").get(random.nextInt(archivosArma.leerListaDeArchivos(".arm").size())));
    }
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregar;
    private javax.swing.JButton botonCrear;
    private javax.swing.JComboBox<String> comboBox;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBienvenido;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblNombreDelVehiculo;
    private javax.swing.JLabel lblTipoDeVehiculo;
    private javax.swing.JLabel lblValidar;
    private javax.swing.JTextField txtNombreDelVehiculo;
    // End of variables declaration//GEN-END:variables
}
