/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinal.ui.formularios;

import com.sun.javafx.scene.SceneHelper;
import java.awt.Frame;
import proyectofinal.CrearArchivos;
import proyectofinal.CrearEscenario;
import proyectofinal.objetos.Arma;
import proyectofinal.objetos.Escenario;
import proyectofinal.objetos.Jugador;
import proyectofinal.objetos.Vehiculo;

/**
 *
 * @author James
 */
public class DialogoNuevoJuego extends javax.swing.JDialog {
    private Jugador jugadorNuevo;
    private FrameEscritorio frameEscritorio;
    private CrearVehiculoDialog crearVehiculoDialog;
    private CrearArchivos<Escenario> archivoEscenario;
    private CrearArchivos<Vehiculo> archivoVehiculos;
    private CrearArchivos<Jugador> archivoJugador;
    private CrearArchivos<Arma> archivoArmas;
    /**
     * Creates new form DialogNuevoJuego
     */
    public DialogoNuevoJuego(java.awt.Frame parent, boolean modal, CrearArchivos<Escenario> archivoEscenario, CrearArchivos<Vehiculo> archivoVehiculos, CrearArchivos<Jugador> archivoJugador, FrameEscritorio frameEscritorio, CrearArchivos<Arma> archivoArmas) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.archivoArmas =archivoArmas;
        this.frameEscritorio = frameEscritorio;
        this.archivoJugador = archivoJugador;
        this.archivoEscenario = archivoEscenario;
        this.archivoVehiculos = archivoVehiculos;
        lblVacio.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBienvenido = new javax.swing.JLabel();
        lblIngresaNombre = new javax.swing.JLabel();
        txtNombreJugador = new javax.swing.JTextField();
        botonCrear = new javax.swing.JButton();
        lblVacio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        lblBienvenido.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblBienvenido.setText("Bienvenido crea tu nombre de usuario para mostar en Batalla");

        lblIngresaNombre.setText("Ingresa el Nombre: ");

        botonCrear.setText("Crear Ahora!!");
        botonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearActionPerformed(evt);
            }
        });

        lblVacio.setForeground(new java.awt.Color(102, 102, 0));
        lblVacio.setText("Campo Vacio");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblBienvenido)
                        .addGap(137, 137, 137))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblVacio)
                        .addGap(177, 177, 177))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIngresaNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNombreJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(264, 264, 264)
                .addComponent(botonCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBienvenido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIngresaNombre)
                    .addComponent(txtNombreJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblVacio)
                .addGap(48, 48, 48)
                .addComponent(botonCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(114, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearActionPerformed
        // TODO add your handling code here:
        if (txtNombreJugador.getText().isEmpty()) {
            lblVacio.setVisible(true);
        }
        lblVacio.setVisible(false);
        jugadorNuevo = new Jugador(txtNombreJugador.getText());
        txtNombreJugador.setText("");
        this.setVisible(false);
        for (int i = 0; i < 3; i++) {
            crearVehiculoDialog = new CrearVehiculoDialog((Frame) this.getParent(), true, jugadorNuevo, archivoVehiculos, archivoArmas);
            crearVehiculoDialog.setVisible(true);
            guardarJugador();
        }
        frameEscritorio.setJugador(jugadorNuevo);
        this.setVisible(false);
    }//GEN-LAST:event_botonCrearActionPerformed

    private void guardarJugador() {
        archivoJugador.crearArchivo(jugadorNuevo, "Jugador", jugadorNuevo.getNombreJugador(), ".jdr");
    }
    
    

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCrear;
    private javax.swing.JLabel lblBienvenido;
    private javax.swing.JLabel lblIngresaNombre;
    private javax.swing.JLabel lblVacio;
    private javax.swing.JTextField txtNombreJugador;
    // End of variables declaration//GEN-END:variables
}
