/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinal.ui.formularios;

import javax.swing.JOptionPane;
import proyectofinal.CrearArchivos;
import proyectofinal.objetos.Arma;

/**
 *
 * @author James
 */
public class DialogCrearArma extends javax.swing.JDialog {
    CrearArchivos<Arma> archivosArmas;
    /**
     * Creates new form DialogCrearArma
     */
    public DialogCrearArma(java.awt.Frame parent, boolean modal, CrearArchivos<Arma> archivosArmas) {
        super(parent, modal);
        this.archivosArmas =archivosArmas;
        initComponents();
        limpiar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBienvenida = new javax.swing.JLabel();
        lblCrear = new javax.swing.JLabel();
        lblNombreDelArma = new javax.swing.JLabel();
        txtNombreDelArma = new javax.swing.JTextField();
        lblCantidad = new javax.swing.JLabel();
        ftxMuniciones = new javax.swing.JFormattedTextField();
        lblCalibre = new javax.swing.JLabel();
        ftxCalibre = new javax.swing.JFormattedTextField();
        lblPrecio = new javax.swing.JLabel();
        ftxPrecio = new javax.swing.JFormattedTextField();
        lblCalidad = new javax.swing.JLabel();
        comboBox = new javax.swing.JComboBox<>();
        lblValidar = new javax.swing.JLabel();
        botonCrear = new javax.swing.JButton();
        lblMayoresA1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        lblBienvenida.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblBienvenida.setText("Bienvenido puedes crear las armas que quieras");

        lblCrear.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCrear.setText("Comienza a Crear:");

        lblNombreDelArma.setText("Nombre del Arma:");

        lblCantidad.setText("Cantidad de balas");

        ftxMuniciones.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ftxMunicionesKeyTyped(evt);
            }
        });

        lblCalibre.setText("Calibre del arma");

        ftxCalibre.setText("      ");
        ftxCalibre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ftxCalibreKeyTyped(evt);
            }
        });

        lblPrecio.setText("Precio:");

        ftxPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ftxPrecioKeyTyped(evt);
            }
        });

        lblCalidad.setText("Calidad:");

        comboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Básica", "Especial", "Épica", "Legendaria" }));

        lblValidar.setForeground(new java.awt.Color(0, 255, 204));
        lblValidar.setText("Todos los campos necesarios");

        botonCrear.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonCrear.setText("Crear");
        botonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearActionPerformed(evt);
            }
        });

        lblMayoresA1.setForeground(new java.awt.Color(0, 255, 204));
        lblMayoresA1.setText("Solo números mayores a 1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBienvenida)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNombreDelArma)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNombreDelArma, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCalibre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ftxCalibre, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCalidad)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCantidad)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ftxMuniciones, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(lblValidar))))
                    .addComponent(lblPrecio)
                    .addComponent(lblCrear)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ftxPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMayoresA1))
                        .addGap(48, 48, 48)
                        .addComponent(botonCrear)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBienvenida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCrear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreDelArma)
                    .addComponent(txtNombreDelArma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCantidad)
                    .addComponent(ftxMuniciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValidar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ftxCalibre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCalibre)
                    .addComponent(lblCalidad)
                    .addComponent(comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecio)
                    .addComponent(ftxPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonCrear)
                    .addComponent(lblMayoresA1))
                .addContainerGap(151, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ftxMunicionesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ftxMunicionesKeyTyped
        // TODO add your handling code here:
        validarNumero(evt);
    }//GEN-LAST:event_ftxMunicionesKeyTyped

    private void ftxCalibreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ftxCalibreKeyTyped
        // TODO add your handling code here:
        validarNumero(evt);
    }//GEN-LAST:event_ftxCalibreKeyTyped

    private void ftxPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ftxPrecioKeyTyped
        // TODO add your handling code here:
        validarNumero(evt);
    }//GEN-LAST:event_ftxPrecioKeyTyped

    private void botonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearActionPerformed
        // TODO add your handling code here:
        if (ftxCalibre.getText().isEmpty() || ftxMuniciones.getText().isEmpty() || ftxPrecio.getText().isEmpty() || txtNombreDelArma.getText().isEmpty()) {
            lblValidar.setVisible(true);
        }else  if (Integer.parseInt(ftxCalibre.getText()) < 2 || Integer.parseInt(ftxMuniciones.getText()) < 2 || Integer.parseInt(ftxPrecio.getText()) < 2) {
            lblMayoresA1.setVisible(true);
        } else {
            Arma arma =new Arma(txtNombreDelArma.getText(), Integer.parseInt(ftxMuniciones.getText()), Integer.parseInt(ftxCalibre.getText()), comboBox.getSelectedItem().toString(), Integer.parseInt(ftxPrecio.getText()));
            try {
                archivosArmas.crearArchivo((Arma)arma.clone(), "Arma", arma.getNombreDelArma() + "_" + arma.getCalidad(), ".arm");
                JOptionPane.showMessageDialog(this, "Creado");
                limpiar();
            } catch (CloneNotSupportedException ex) {
                System.out.println("No se puede clonar");
            }
        }
    }//GEN-LAST:event_botonCrearActionPerformed

    public void limpiar() {
        txtNombreDelArma.setText("");
        ftxCalibre.setText("");
        ftxMuniciones.setText("");
        ftxPrecio.setText("");
        lblValidar.setVisible(false);
        lblMayoresA1.setVisible(false);
        comboBox.setSelectedIndex(0);
    }
    
    public void validarNumero(java.awt.event.KeyEvent evt){
        char value = evt.getKeyChar();
        if (value <'0' || value >'9') evt.consume();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCrear;
    private javax.swing.JComboBox<String> comboBox;
    private javax.swing.JFormattedTextField ftxCalibre;
    private javax.swing.JFormattedTextField ftxMuniciones;
    private javax.swing.JFormattedTextField ftxPrecio;
    private javax.swing.JLabel lblBienvenida;
    private javax.swing.JLabel lblCalibre;
    private javax.swing.JLabel lblCalidad;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblCrear;
    private javax.swing.JLabel lblMayoresA1;
    private javax.swing.JLabel lblNombreDelArma;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblValidar;
    private javax.swing.JTextField txtNombreDelArma;
    // End of variables declaration//GEN-END:variables
}
