/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinal.ui.formularios;

import proyectofinal.objetos.Escenario;
import proyectofinal.objetos.Arma;
import javax.swing.JDesktopPane;
import javax.swing.JFrame;
import proyectofinal.CrearArchivos;
import proyectofinal.objetos.Jugador;
import proyectofinal.objetos.Vehiculo;

/**
 *
 * @author James
 */
public class FrameMenu extends javax.swing.JInternalFrame {
    private DialogCrearArma crearArma;
    private DialogoPedirEscenario pedirEscenario;
    private DialogTiendaOpciones dialogTiendaOpciones;
    private JDesktopPane panelDeEscritorio;
    private JFrame framePrincipal;
    private Jugador jugador;
    private CrearArchivos<Vehiculo> archivoVehiculos;
    private CrearArchivos<Arma> archivosArmas;
    private CrearArchivos<Escenario> archivoEscenario;
    /**
     * Creates new form MenuPrincipalFrame
     */
    public FrameMenu(JFrame framePrincipal, CrearArchivos<Escenario> archivoEscenario, CrearArchivos<Arma> archivosArmas, JDesktopPane panelDeEscritorio, CrearArchivos<Vehiculo> archivoVehiculos, Jugador jugador) {
        initComponents();
        this.jugador = jugador;
        this.archivoVehiculos = archivoVehiculos;
        this.archivosArmas = archivosArmas;
        this.archivoEscenario = archivoEscenario;
        crearArma = new DialogCrearArma(framePrincipal, true, archivosArmas);
        this.panelDeEscritorio = panelDeEscritorio;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        butonBatalla = new javax.swing.JButton();
        botonCrear = new javax.swing.JButton();
        botonTienda = new javax.swing.JButton();
        botonReportes = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        lblImagen = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);

        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        butonBatalla.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        butonBatalla.setText("Batalla");
        butonBatalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonBatallaActionPerformed(evt);
            }
        });
        panel.add(butonBatalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 160, 70));

        botonCrear.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonCrear.setText("Crear");
        botonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearActionPerformed(evt);
            }
        });
        panel.add(botonCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 150, 70));

        botonTienda.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonTienda.setText("Tienda");
        botonTienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTiendaActionPerformed(evt);
            }
        });
        panel.add(botonTienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 361, 150, 70));

        botonReportes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonReportes.setText("Reportes");
        panel.add(botonReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 30));

        botonSalir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonSalir.setText("Salir");
        panel.add(botonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 70));
        panel.add(lblImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonTiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTiendaActionPerformed
        // TODO add your handling code here:
        dialogTiendaOpciones  = new DialogTiendaOpciones(framePrincipal, true, jugador, archivoVehiculos, archivosArmas);
        this.setVisible(false);
        dialogTiendaOpciones.setVisible(true);
    }//GEN-LAST:event_botonTiendaActionPerformed

    private void botonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearActionPerformed
        // TODO add your handling code here:
        crearArma.setVisible(true);
    }//GEN-LAST:event_botonCrearActionPerformed

    private void butonBatallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonBatallaActionPerformed
        // TODO add your handling code here:
        this.pedirEscenario = new DialogoPedirEscenario(framePrincipal, true, archivoEscenario, panelDeEscritorio, jugador);
        this.setVisible(false);
        pedirEscenario.setVisible(true);
    }//GEN-LAST:event_butonBatallaActionPerformed

    public void setJugador(Jugador jugador) {
        this.jugador = jugador;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCrear;
    private javax.swing.JButton botonReportes;
    private javax.swing.JButton botonSalir;
    private javax.swing.JButton botonTienda;
    private javax.swing.JButton butonBatalla;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
